### ISSUE TITLE
“trait” 或许应该翻译为 “契头”

### ISSUE THREAD

**Issue by varphone** [rust-lang-cn/english-chinese-glossary-of-rust#12]
契头 = 契约的头部，只包含了宗旨，并不包含其其他条款，与 `trait` 的本质很接近，而且读音也比较接近。

**Comment by ZhangHanDong** [comment]
现在通用的翻译是 「特质」。

不要再生造词了，你造个「契头」， 还得给别人再解释这个「契头」是什么意思。

最好是一个通用的词语来解释trait，而不是通过trait来理解这个词。

比如，我们看到「特质」，没有学过trait的人，也大概能明白是什么意思。能帮助它去理解trait。

但是你起个「契头」，这根本不是一个通用的词，别人得先理解了 trait，才能明白你这个词是啥意思。本末倒置了。

不是个好词。
