### ISSUE TITLE
variant 或许应译作变体（或者枚举值）

### ISSUE THREAD

**Issue by lihsai0** [rust-lang-cn/english-chinese-glossary-of-rust#19]
variant 的英文释义为「a thing that is a slightly different form or type of sth else」

和变量感觉差挺多的

**Comment by George-Miao** [comment]
以及新增一个 enum 的翻译？比如说枚举。

**Comment by lihsai0** [comment]
> 以及新增一个 enum 的翻译？比如说枚举。

enum 已经有了，毕竟只是缩写

[enumeration 枚举](https://github.com/rust-lang-cn/english-chinese-glossary-of-rust/blob/master/rust-glossary.md#:~:text=enumeration,%E6%9E%9A%E4%B8%BE)

**Comment by ZhangHanDong** [comment]
感谢反馈，第二版中打算用这个

**Comment by lihsai0** [comment]
fixed by f9629d2
