### ISSUE TITLE
baroque macro  是什么？

### ISSUE THREAD

**Issue by jschwe** [rust-lang-cn/english-chinese-glossary-of-rust#25]
Glossary 里面有：
baroque macro 	巴洛克宏 

我不知道baroque macro是什么，谷歌上也没有什么结果。我看了Glossary 里没有翻译[declarative macros](https://doc.rust-lang.org/book/ch19-06-macros.html#declarative-macros-with-macro_rules-for-general-metaprogramming)，是不是同样个东西？

**Comment by ZhangHanDong** [comment]
@jschwe `baroque macro` 这个术语你在哪里看到的？

**Comment by ZhangHanDong** [comment]
Rust 里没这种玩意。  翻译的问题吧， baroque macro   是说 奇形怪状的宏形式

**Comment by ZhangHanDong** [comment]
你可以发个pr把它删掉

**Comment by jschwe** [comment]
我发了个PR.

> 可以加上declarative macros 术语

我是用这表为了学中文的术语，所以我根本不知道怎么翻译declarative macro :(

**Comment by ZhangHanDong** [comment]
declarative macros  声明宏

**Comment by Jiuyong** [comment]
> https://github.com/rust-lang-cn/english-chinese-glossary-of-rust/blob/509c0e8e1a8cec3028aff312875ab6e64fff82c7/rust-glossary.md?plain=1#L32

这种音译还不如不翻译了，保持原样更好。
