### ISSUE TITLE
我又想出来一个灵感，大家觉得如何？

### ISSUE THREAD

**Issue by Jiuyong** [rust-lang-cn/english-chinese-glossary-of-rust#30]
Rust 这么好的语言，我觉得改给她起一个中文名称，我想翻译成为 "秀“。大家觉得如何？
兼顾意译（锈菌Rust）以及信达雅（Rust的确很优秀）。
我是在认真讨论。
请一些管理者不要以权谋私阻止别的rust爱好者讨论翻译。
也请一些人不要问”为什么要翻译“这种来杠的问题。
至于要不要别的语言名称要不要翻译成中文，那是别的语言的事，请不要用这个杠，
你真想讨论，请去你举例的语言和他们讨论，我没兴趣。
因为在翻译QQ群提出这个话题，被T了，所以在这里发了点感慨，请大家见谅。
但是目的还是想提出这个想法，而不是和某些人辨割输赢。
有人以列表 Rust 不翻译为由来怼我，请问这是理由吗？
这个列表是人定的吧？而且特质开始也是不译的吧？
找理由也要有点诚意，心胸狭隘的打击报复别人，也要做好表面文章，别这么敷衍好吗？

**Comment by Jiuyong** [comment]
就像你喜欢的宠物，你一定会给它起一个名字，难道不是吗？

**Comment by ZhangHanDong** [comment]
你想怎么样那是你自己的事。
但不要强迫别人跟你一起。

**Comment by Jiuyong** [comment]
> 你想怎么样那是你自己的事。 但不要强迫别人跟你一起。

这个自然，所以我只是发出来，希望感兴趣的人能一起讨论，不喜勿喷，相当于。

**Comment by Jiuyong** [comment]
> 你想怎么样那是你自己的事。 但不要强迫别人跟你一起。

张老师，越想越觉得你这话说得很对！
谢谢指教！受益匪浅！

**Comment by Jiuyong** [comment]
> Rust 这么好的语言，我觉得改给她起一个中文名称，我想翻译成为 "秀“。大家觉得如何？ 兼顾意译（锈菌Rust）以及信达雅（Rust的确很优秀）。 我是在认真讨论。 请一些管理者不要以权谋私阻止别的rust爱好者讨论翻译。 也请一些人不要问”为什么要翻译“这种来杠的问题。 至于要不要别的语言名称要不要翻译成中文，那是别的语言的事，请不要用这个杠， 你真想讨论，请去你举例的语言和他们讨论，我没兴趣。 因为在翻译QQ群提出这个话题，被T了，所以在这里发了点感慨，请大家见谅。 但是目的还是想提出这个想法，而不是和某些人辨割输赢。 有人以列表 Rust 不翻译为由来怼我，请问这是理由吗？ 这个列表是人定的吧？而且特质开始也是不译的吧？ 找理由也要有点诚意，心胸狭隘的打击报复别人，也要做好表面文章，别这么敷衍好吗？

希望多几个踩我的能看到：随便搜了下。
你们反感我翻译成“秀”，结果，网上粉丝用脚投票，很多都翻译成“腐蚀”，岂不是更尴尬？
不信你们可以搜下QQ群之类的。
