### ISSUE TITLE
建议将 crate 翻译成「单元包」

### ISSUE THREAD

**Issue by Integral-Tech** [rust-lang-cn/english-chinese-glossary-of-rust#35]
crate 是 Rust 的基本编译单元，package 提供一系列功能的一个或者多个 crate。
因此个人认为 crate 翻译成「单元包」比较合适。

参考资料：《Rust 权威指南》

**Comment by zuoxinyu** [comment]
提议一个翻译原则：
1. 非 Rust 独有的东西，如类型系统、语法、语义、异步等语言特性，尽量参考现有的其它主流译法，如「生命周期」，虽然不是完全准确，但已经是 de facto 的译法。
2. Rust 独有的机制，如 Cargo 和相关的包管理中的名词以及 Rust 语言本身，直译没有意义的词，倾向于不译。
